module.exports = [
  // Основные иконки
  { name: "HomeOutlined", keywords: ["дом", "главная", "home"] },
  { name: "UserOutlined", keywords: ["пользователь", "человек", "user"] },
  { name: "SettingOutlined", keywords: ["настройки", "settings", "конфиг"] },
  { name: "SearchOutlined", keywords: ["поиск", "search", "лупа"] },
  { name: "MenuOutlined", keywords: ["меню", "menu", "гамбургер"] },
  { name: "CloseOutlined", keywords: ["закрыть", "close", "крестик"] },
  { name: "CheckOutlined", keywords: ["галочка", "check", "отметка"] },
  { name: "PlusOutlined", keywords: ["плюс", "plus", "добавить"] },
  { name: "MinusOutlined", keywords: ["минус", "minus", "удалить"] },
  { name: "EditOutlined", keywords: ["редактировать", "edit", "карандаш"] },
  { name: "DeleteOutlined", keywords: ["удалить", "delete", "корзина"] },
  { name: "SaveOutlined", keywords: ["сохранить", "save", "диск"] },
  { name: "DownloadOutlined", keywords: ["скачать", "download", "стрелка вниз"] },
  { name: "UploadOutlined", keywords: ["загрузить", "upload", "стрелка вверх"] },
  { name: "CopyOutlined", keywords: ["копировать", "copy", "дублировать"] },
  { name: "ShareAltOutlined", keywords: ["поделиться", "share", "отправить"] },
  { name: "HeartOutlined", keywords: ["сердце", "heart", "лайк"] },
  { name: "StarOutlined", keywords: ["звезда", "star", "избранное"] },
  { name: "LikeOutlined", keywords: ["лайк", "like", "нравится"] },
  { name: "DislikeOutlined", keywords: ["дизлайк", "dislike", "не нравится"] },
  
  // Навигация
  { name: "LeftOutlined", keywords: ["влево", "left", "назад"] },
  { name: "RightOutlined", keywords: ["вправо", "right", "вперед"] },
  { name: "UpOutlined", keywords: ["вверх", "up", "стрелка вверх"] },
  { name: "DownOutlined", keywords: ["вниз", "down", "стрелка вниз"] },
  { name: "ArrowLeftOutlined", keywords: ["стрелка влево", "arrow left"] },
  { name: "ArrowRightOutlined", keywords: ["стрелка вправо", "arrow right"] },
  { name: "ArrowUpOutlined", keywords: ["стрелка вверх", "arrow up"] },
  { name: "ArrowDownOutlined", keywords: ["стрелка вниз", "arrow down"] },
  { name: "ReloadOutlined", keywords: ["обновить", "reload", "перезагрузить"] },
  { name: "SyncOutlined", keywords: ["синхронизация", "sync", "обновить"] },
  
  // Коммуникация
  { name: "MailOutlined", keywords: ["почта", "mail", "email"] },
  { name: "PhoneOutlined", keywords: ["телефон", "phone", "звонок"] },
  { name: "MessageOutlined", keywords: ["сообщение", "message", "чат"] },
  { name: "CommentOutlined", keywords: ["комментарий", "comment", "отзыв"] },
  { name: "NotificationOutlined", keywords: ["уведомление", "notification", "звонок"] },
  { name: "BellOutlined", keywords: ["колокольчик", "bell", "уведомление"] },
  { name: "SoundOutlined", keywords: ["звук", "sound", "аудио"] },
  { name: "VideoCameraOutlined", keywords: ["видео", "video", "камера"] },
  { name: "CameraOutlined", keywords: ["камера", "camera", "фото"] },
  { name: "PictureOutlined", keywords: ["картинка", "picture", "изображение"] },
  
  // Файлы и папки
  { name: "FileOutlined", keywords: ["файл", "file", "документ"] },
  { name: "FolderOutlined", keywords: ["папка", "folder", "директория"] },
  { name: "FolderOpenOutlined", keywords: ["открытая папка", "folder open"] },
  { name: "FileTextOutlined", keywords: ["текстовый файл", "file text"] },
  { name: "FilePdfOutlined", keywords: ["pdf файл", "file pdf"] },
  { name: "FileImageOutlined", keywords: ["изображение", "file image"] },
  { name: "FileZipOutlined", keywords: ["архив", "file zip", "сжатый"] },
  { name: "FileExcelOutlined", keywords: ["excel", "file excel", "таблица"] },
  { name: "FileWordOutlined", keywords: ["word", "file word", "документ"] },
  { name: "FilePptOutlined", keywords: ["powerpoint", "file ppt", "презентация"] },
  
  // Социальные сети
  { name: "FacebookOutlined", keywords: ["facebook", "фейсбук"] },
  { name: "TwitterOutlined", keywords: ["twitter", "твиттер"] },
  { name: "InstagramOutlined", keywords: ["instagram", "инстаграм"] },
  { name: "LinkedinOutlined", keywords: ["linkedin", "линкедин"] },
  { name: "YoutubeOutlined", keywords: ["youtube", "ютуб"] },
  { name: "GithubOutlined", keywords: ["github", "гитхаб"] },
  { name: "GoogleOutlined", keywords: ["google", "гугл"] },
  { name: "WechatOutlined", keywords: ["wechat", "вечат"] },
  { name: "WeiboOutlined", keywords: ["weibo", "вейбо"] },
  { name: "QqOutlined", keywords: ["qq", "кьюкью"] },
  
  // Интерфейс
  { name: "EyeOutlined", keywords: ["глаз", "eye", "просмотр"] },
  { name: "EyeInvisibleOutlined", keywords: ["скрытый глаз", "eye invisible", "скрыть"] },
  { name: "LockOutlined", keywords: ["замок", "lock", "заблокировано"] },
  { name: "UnlockOutlined", keywords: ["открытый замок", "unlock", "разблокировано"] },
  { name: "KeyOutlined", keywords: ["ключ", "key", "пароль"] },
  { name: "SafetyOutlined", keywords: ["безопасность", "safety", "щит"] },
  { name: "ShieldOutlined", keywords: ["щит", "shield", "защита"] },
  { name: "InfoCircleOutlined", keywords: ["информация", "info", "справка"] },
  { name: "QuestionCircleOutlined", keywords: ["вопрос", "question", "помощь"] },
  { name: "ExclamationCircleOutlined", keywords: ["восклицание", "exclamation", "внимание"] },
  { name: "WarningOutlined", keywords: ["предупреждение", "warning", "осторожно"] },
  { name: "StopOutlined", keywords: ["стоп", "stop", "остановить"] },
  { name: "PlayCircleOutlined", keywords: ["воспроизведение", "play", "пуск"] },
  { name: "PauseCircleOutlined", keywords: ["пауза", "pause", "остановить"] },
  { name: "StepForwardOutlined", keywords: ["следующий", "step forward", "далее"] },
  { name: "StepBackwardOutlined", keywords: ["предыдущий", "step backward", "назад"] },
  { name: "FastForwardOutlined", keywords: ["быстрая перемотка", "fast forward"] },
  { name: "FastBackwardOutlined", keywords: ["быстрая перемотка назад", "fast backward"] },
  
  // Время и календарь
  { name: "ClockCircleOutlined", keywords: ["время", "clock", "часы"] },
  { name: "CalendarOutlined", keywords: ["календарь", "calendar", "дата"] },
  { name: "HistoryOutlined", keywords: ["история", "history", "журнал"] },
  { name: "ScheduleOutlined", keywords: ["расписание", "schedule", "план"] },
  { name: "FieldTimeOutlined", keywords: ["время поля", "field time"] },
  { name: "HourglassOutlined", keywords: ["песочные часы", "hourglass", "таймер"] },
  
  // Настройки и инструменты
  { name: "ToolOutlined", keywords: ["инструмент", "tool", "настройки"] },
  { name: "WrenchOutlined", keywords: ["ключ", "wrench", "настройка"] },
  { name: "BugOutlined", keywords: ["баг", "bug", "ошибка"] },
  { name: "CodeOutlined", keywords: ["код", "code", "программирование"] },
  { name: "ApiOutlined", keywords: ["api", "интерфейс"] },
  { name: "DatabaseOutlined", keywords: ["база данных", "database", "хранилище"] },
  { name: "CloudOutlined", keywords: ["облако", "cloud", "интернет"] },
  { name: "CloudUploadOutlined", keywords: ["загрузка в облако", "cloud upload"] },
  { name: "CloudDownloadOutlined", keywords: ["скачивание из облака", "cloud download"] },
  { name: "CloudSyncOutlined", keywords: ["синхронизация облака", "cloud sync"] },
  
  // Транспорт
  { name: "CarOutlined", keywords: ["машина", "car", "автомобиль"] },
  { name: "TruckOutlined", keywords: ["грузовик", "truck", "доставка"] },
  { name: "RocketOutlined", keywords: ["ракета", "rocket", "запуск"] },
  { name: "AirplaneOutlined", keywords: ["самолет", "airplane", "полет"] },
  { name: "TrainOutlined", keywords: ["поезд", "train", "железная дорога"] },
  { name: "ShipOutlined", keywords: ["корабль", "ship", "море"] },
  { name: "BikeOutlined", keywords: ["велосипед", "bike", "велосипед"] },
  { name: "BusOutlined", keywords: ["автобус", "bus", "транспорт"] },
  
  // Еда и напитки
  { name: "CoffeeOutlined", keywords: ["кофе", "coffee", "напиток"] },
  { name: "AppleOutlined", keywords: ["яблоко", "apple", "фрукт"] },
  { name: "GiftOutlined", keywords: ["подарок", "gift", "сюрприз"] },
  { name: "CakeOutlined", keywords: ["торт", "cake", "сладость"] },
  { name: "FireOutlined", keywords: ["огонь", "fire", "пламя"] },
  { name: "ThunderboltOutlined", keywords: ["молния", "thunderbolt", "энергия"] },
  
  // Природа
  { name: "SunOutlined", keywords: ["солнце", "sun", "день"] },
  { name: "MoonOutlined", keywords: ["луна", "moon", "ночь"] },
  { name: "CloudOutlined", keywords: ["облако", "cloud", "небо"] },
  { name: "EnvironmentOutlined", keywords: ["окружение", "environment", "природа"] },
  { name: "GlobalOutlined", keywords: ["глобус", "global", "мир"] },
  { name: "CompassOutlined", keywords: ["компас", "compass", "направление"] },
  { name: "FlagOutlined", keywords: ["флаг", "flag", "страна"] },
  { name: "HomeOutlined", keywords: ["дом", "home", "жилье"] },
  { name: "BankOutlined", keywords: ["банк", "bank", "финансы"] },
  { name: "ShopOutlined", keywords: ["магазин", "shop", "торговля"] },
  { name: "MedicineBoxOutlined", keywords: ["медицина", "medicine", "здоровье"] },
  { name: "ExperimentOutlined", keywords: ["эксперимент", "experiment", "наука"] },
  { name: "BulbOutlined", keywords: ["лампочка", "bulb", "идея"] },
  { name: "BookOutlined", keywords: ["книга", "book", "чтение"] },
  { name: "ReadOutlined", keywords: ["чтение", "read", "изучение"] },
  { name: "EditOutlined", keywords: ["редактирование", "edit", "изменение"] },
  { name: "PrinterOutlined", keywords: ["принтер", "printer", "печать"] },
  { name: "ScanOutlined", keywords: ["сканирование", "scan", "сканер"] },
  { name: "BarcodeOutlined", keywords: ["штрихкод", "barcode", "код"] },
  { name: "QrcodeOutlined", keywords: ["qr код", "qrcode", "код"] }
];
